### ISSUE TITLE
Pull down to refresh 

### ISSUE THREAD

**Issue by cdysthe** [Tunous/Dawn#105]
With an app so focused on gestures it would be natural to have pull down to refresh working. Please include this and keep this app going!

**Comment by Tunous** [comment]
I don’t think that such a gesture would fit the app. As [previously stated](https://www.reddit.com/r/GetDank/comments/8iojk4/feature_requests/dyuw5ar/?utm_source=share&utm_medium=ios_app&utm_name=iossmf) by saket vertical gestures are reserved for dismissing and we should stay with this convention.

**Comment by vishnumad** [comment]
What is the alternative way of refreshing that Saket was talking about in the Reddit comment?

**Comment by Tunous** [comment]
You can refresh by pressing on the refresh button located in the top toolbar in case of submission list and under self-post for comments view.
