### ISSUE TITLE
Trying to open page in external browser might result in crash

### ISSUE THREAD

**Issue by Tunous** [Tunous/Dawn#108]
# Description
**Precondition:** A user has no installed browser

When attempting to open page in external browser Dawn crashes.

**To Reproduce**
1. Go to any link which will open in internal browser
2. Click on more options top bar item
3. Click on 'Open in browser' item

**Expected behavior**
Most likely an error message telling the user that no browser was found should be displayed.

# Hints for fixing

The issue described here is caused by the following line:

https://github.com/Tunous/Dawn/blob/77a667949607b5e27e28dde11d8cb83c22243c33/app/src/main/java/me/saket/dank/ui/webview/WebViewActivity.java#L117

In this case `ActivityNotFoundException` exception is thrown which crashes the app. The issue can occur everywhere where intent from `Intents.createForOpeningUrl` is passed to `Context.startActivity`. We should instead check whether the created intent can be opened or handle the exception and inform the user about the problem.

**Comment by Tunous** [comment]
Also can happen here:

https://github.com/Tunous/Dawn/blob/77a667949607b5e27e28dde11d8cb83c22243c33/app/src/main/java/me/saket/dank/ui/webview/ChromeCustomTabsForwardingActivity.java#L43

**Comment by SubhrajyotiSen** [comment]
Has this been resolved? If not, I can pick it up

**Comment by Tunous** [comment]
@SubhrajyotiSen It has not been fixed by anyone yet. Feel free to give it a try.
