### ISSUE TITLE
Can't see post's score if user flair is too long 

### ISSUE THREAD

**Issue by elenmerbau** [Tunous/Dawn#122]
![Untitled](https://user-images.githubusercontent.com/23418072/68721646-3bf45100-05dd-11ea-8f73-bcd3dacbf24c.png)

**Comment by Tunous** [comment]
Any suggestions how we could fix that?

I can think of these options:
- Move the score before user flair
- Truncate user flair instead of score
- Wrap comment information (bad idea probably)

**Comment by elenmerbau** [comment]
Maybe just allow post information to use secondary row if needed? It's how Sync for reddit solved it. You will get all the info and sacrifice just a little of vertical space. Moving the score in addition to that would be nice as well, imo: your eyes won't jump all the time searching for the score if there are a lot of posts with long user flairs. 

I made some examples, I am not a UI designer by any means, maybe someone will come up with a better solution.
First one is with default score position:
![2 rows, default score position - Copy](https://user-images.githubusercontent.com/23418072/68817274-6a406200-06ab-11ea-8503-6f26ec192cb7.png)
Second is with moved score position:
![2 rows, moved score position - Copy](https://user-images.githubusercontent.com/23418072/68817311-8a702100-06ab-11ea-818c-47a35e94daca.png)
