### ISSUE TITLE
[RFC] Image viewer double-open in submissions

### ISSUE THREAD

**Issue by AbsurdlySuspicious** [Tunous/Dawn#171]
`gesture-views` update from 2.2.0 to 2.5.2 (d76fdfa81da8f3cf05c3d3b65018690d0eb680fe) caused duplicate event emission here:

https://github.com/Tunous/Dawn/blob/f1f5f9db2922ec5234a4b9c7439568836ecd94d5/app/src/main/java/me/saket/dank/ui/submission/SubmissionPageLayout.java#L969

which results in image viewer opening twice.
2.6.0 also doesn't fix this.

Possible solutions are
- Downgrade and lock gesture-views version
- Use immediate debounce implementation for RxJava (as in https://stackoverflow.com/a/41969532). This would also help to prevent viewers from opening twice if user clicks too fast

I intended to open a PR, but I'm not sure which way is more appropriate.
Reporting this to gesture-views would also be nice, but I don't have enough knowledge of Dawn's codebase to investigate any further

**Comment by AbsurdlySuspicious** [comment]
Updated version also prevents submission activity from being swapped back if `contentImageView` is scrollable

**Comment by Tunous** [comment]
If there are multiple issues I would suggest downgrading the dependency and reporting in their issue tracker what potentially could be wrong. 

It's worth checking also versions in between these too to find the one where it stopped working. 

I don't know the codebase too well either so I won't be of much help here.

**Comment by AbsurdlySuspicious** [comment]
I've found the first bad versions already:

- 2.3.2 - broken swipe
- 2.4.0 - duplicating events

I think that it might be not a bug but rather incorrect use of the library within the client itself.
And about downgrading, is there a way to blacklist it for dependabot?

**Comment by Tunous** [comment]
https://dependabot.com/docs/config-file/#ignored_updates

This looks to be something that could be used.
