### ISSUE TITLE
external media hosting links not working

### ISSUE THREAD

**Issue by angriness-sleek** [Tunous/Dawn#211]
**Describe the bug**
Imgur, gyfcat, redgifs links just end up with something went wrong or the internet doesn't seems to be working and try again doesn't work, not always but many of the times. Especially video links, almost all video posts not hosted on reddit don't work.

**To Reproduce**
1. Go to any media sub
2. Click on a post of Imgur or gyfcat
3. See error

**Expected behavior**
External hosting links should work fine like they did in previous versions

**Screenshots**
![IMG_20200522_020646_539](https://user-images.githubusercontent.com/62484249/82603846-e1970700-9ba2-11ea-8840-d3e1bc324457.jpg)

**Smartphone (please complete the following information):**
 - Device: Mi A2
 - OS: Android 10
 - Version 0.9.1

**Additional context**

**Comment by Tunous** [comment]
@AbsurdlySuspicious do you think that your fixes include all of mentioned cases here or are we missing something? For what is worth, the post from image above is fixed for me on latest debug version.

**Comment by AbsurdlySuspicious** [comment]
Fix for reddit-hosted videos might as well have fixed issues with other hosts, including gfycat. Though I haven't touched gfycat url parser at all.  

Anyway, I think we need actual submission links that causes problems for OP to be sure

**Comment by AbsurdlySuspicious** [comment]
Seems like gfycat.com/gifs/* links causes 401 response from somewhere (api, I guess?)

As for other cases, I think they should work ok now, but then again, can't say for sure without any links

**Comment by angriness-sleek** [comment]
As for the links, I just went to 'popular' to look for them and here's 4 v.redd.it links I gathered from a little scrolling:
https://reddit.com/r/Damnthatsinteresting/comments/goox91/cutting_aloe_vera_leaf/

https://reddit.com/r/WatchPeopleDieInside/comments/gosq3g/just_doing_my_thing/

https://reddit.com/r/Damnthatsinteresting/comments/gonfnb/a_way_to_create_a_useless_loop_out_of_a_useless/

https://reddit.com/r/WatchPeopleDieInside/comments/goso4u/never_lose_focus/

The v.redd.it links in these post give me an error. For gyfcat and Imgur, I'll send...

**Comment by angriness-sleek** [comment]
For what its worth, i've blocked bugsnag.com and all analytics system wide

**Comment by angriness-sleek** [comment]
Alright I know this is stupid, I apologize for a complete change of cases, but now im browsing r/gif to collect examples to share and suddenly every external link is working but none v.redd.it link is working... I can send every v.redd.it but you get the idea I think, none is working.

**Comment by AbsurdlySuspicious** [comment]
> I can send every v.redd.it but you get the idea I think, none is working.
Sure thing, just one link that causes problems for each media hosting is enough.

Imgur and v.redd.it are fixed in master already and will be coming with next release. Gfycat bug is confirmed, I'll drop its issue number here. 

Please report if this problem occurs with any other hosting. I think separate issue for each hosting will be more appropriate. No need to fill whole report template for for this particular error, just drop reddit thread link and hosting name

**Comment by MrSunnyshine** [comment]
Same issue, I don't think any v.reddit links work ex:
https://v.redd.it/w85o0813ah151
From https://reddit.com/r/PublicFreakout/comments/gs3cc7/large_group_of_officers_lined_up_in_front_of/

**Comment by angriness-sleek** [comment]
For gyfcat links, it won't be appropriate for me to send an Nsfw link here, but the ones that redirect to RedGif, don't work

**Comment by AbsurdlySuspicious** [comment]
> Pure RedGif links also do not work

Seems like Redgif api is a little different from gfycat and will require new resolver

> the ones that redirect to RedGif, don't work

Can you provide one of these? So we at least can fallback it to webview until new resolver is done

**Comment by AbsurdlySuspicious** [comment]
Giphy: #217
Gfycat: #218

**Comment by AbsurdlySuspicious** [comment]
Redgifs (incl. redirects): #219 
I think we can close this after merge

**Comment by Tunous** [comment]
Great work @AbsurdlySuspicious. I’ll try to upload a new version to play store this week.
