### ISSUE TITLE
Data saving options

### ISSUE THREAD

**Issue by Tunous** [Tunous/Dawn#241]
> like prefer loading low quality image/video if possible

https://reddit.com/r/GetDank/comments/h0dyvp/feature_request/

**Comment by AbsurdlySuspicious** [comment]
But there is one already :D

**Comment by AbsurdlySuspicious** [comment]
![](https://i.imgur.com/Pozmbo9.jpg)

**Comment by Tunous** [comment]
Since original request was deleted and we already have some options I'm closing this as invalid.
