### ISSUE TITLE
Double tap back button to exit

### ISSUE THREAD

**Issue by MF-Debug** [Tunous/Dawn#253]
**Is your feature request related to a problem? Please describe.**
It's kind of frustrating when I'm on the front page browsing & accidentally click the back button. The app closes immediately upon this.

**Describe the solution you'd like**
After pressing the back button once, show a toast dialogue like "press again to exit". Now if anyone actually wishes to close the app, pressing the back button again will close the app.

**Describe alternatives you've considered**
Perhaps showing a dialogue box with exit option instead of double tapping to confirm exiting the app.

**Comment by Tunous** [comment]
Duplicate of https://github.com/Tunous/Dawn/issues/120

**Comment by Tunous** [comment]
I’ve copied your nice description to the other issue and am closing this one.
