### ISSUE TITLE
Android Q (10) Autofill Crashing

### ISSUE THREAD

**Issue by hysrx** [Tunous/Dawn#271]
**Describe the bug**
MYKI, a password manager app causes the app to crash once it tries to auto

**To Reproduce**
1. Go to Login button
2. Click on username field in Reddit login pop-up
3. Use password manager to autofill in information

**Expected behavior**
The password and username to appear in the respective boxes

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S7 edge (hero2lte)
 - OS: crDroid / Android / AOSP
 - Version 10 (Android) 6.6 (crDroid)

**Additional context**
- I am using the Bromite Systemless WebView Magisk Module by linuxandria, which could be causing this issue
- dogbin Crash Logs: https://del.dog/iticuretin.txt

**Comment by AbsurdlySuspicious** [comment]
Can you try this with webview module disabled so we can narrow down possible causes for this?

**Comment by hysrx** [comment]
Hey! Really sorry for the delay in response. I disabled the module and installed Google's official WebView app from the Play Store.

I still had the same issue.
https://del.dog/agucyfubac.txt

**Comment by AbsurdlySuspicious** [comment]
Will autofill work for this link in standalone chromium or other webview?

`https://www.reddit.com/login/.compact?dest=https%3A%2F%2Fwww.reddit.com%2Fapi%2Fv1%2Fauthorize.compact%3Fclient_id%3PLACEHOLDER%26response_type%3Dcode%26state%3Dplaceholder%26redirect_uri%3Dhttp%253A%252F%252Fdawn.thanel.me%26duration%3Dpermanent%26scope%3Daccount%2Bedit%2Bhistory%2Bidentity%2Bmysubreddits%2Bprivatemessages%2Bread%2Breport%2Bsave%2Bsubmit%2Bsubscribe%2Bvote%2Bwikiread`

No need to actually press login, of course

**Comment by msfjarvis** [comment]
I don't believe this is a bug in Dawn because I've been Autofilling credentials into it using [my own password manager](https://msfjarvis.dev/aps) with zero crashes, on both Android 10 and 11. Also, the login form is straight from Reddit which is implementing Autofill correctly. Maybe your password manager needs to be provided with this bug report instead.
