### ISSUE TITLE
Request: show full image layout

### ISSUE THREAD

**Issue by Donkey-Doug** [Tunous/Dawn#272]
It would be nice if there was an option to show entire images in subreddits. The current choices are disabled, thumbnail and large. I would like a fourth option, "full".

Large view in Dawn:
![Screenshot_2020-07-10-00-48-53-274_me thanel dank](https://user-images.githubusercontent.com/50382414/87098304-42f46180-c247-11ea-8705-5f9a856e0008.jpg)

Example of requested "full" view from reddit mobile website:
![Screenshot_2020-07-10-00-48-43-607_org mozilla fenix](https://user-images.githubusercontent.com/50382414/87098352-58698b80-c247-11ea-800a-6cc4e8d73254.jpg)

**Comment by AbsurdlySuspicious** [comment]
Already in work: PR #207

**Comment by Donkey-Doug** [comment]
You are correct.
