### ISSUE TITLE
Unable to save bookmarks.

### ISSUE THREAD

**Issue by sert121** [Tunous/Dawn#307]
**Describe the bug**
Bookmarks don't get registered.

**To Reproduce**
1. Slide across a post until you see a star
2. Leave it, to register a post as a bookmark
3. Login to reddit via Chrome 
4. Check My bookmarks 
5. Bookmark isn't registered 

**Expected behavior**
The bookmarks should show up in original reddit website : reddit.com in the respective profile. 

**Smartphone 
 - Device: Redmi 4X
 - OS: [e.g. Android 10]

**Comment by Tunous** [comment]
Duplicate of https://github.com/Tunous/Dawn/issues/73

**Comment by Tunous** [comment]
Copied description to that other issue.
