### ISSUE TITLE
Jitpack stopped resolving dependency

### ISSUE THREAD

**Issue by AbsurdlySuspicious** [Tunous/Dawn#311]
Jitpack now returns 404 for `com.github.rahatarmanahmed:circularprogressview:2.5.0`, seems like this is long-standing jitpack `file not found, build ok` bug. It's now impossible to build Dawn with clean cache or without building the lib manually

**Comment by AbsurdlySuspicious** [comment]
I think most obvious solution is to create a github org and move Dawn here, so we can collect forks of unmaintained libraries in one place. At the very least, changing repo address should bump jitpack build, but it would be best to eventually setup workflow for uploading such libraries to jcenter

**Comment by AbsurdlySuspicious** [comment]
Initial issue is fixed, but question where to keep JRAW and possibly other libs forks still stays

**Comment by Tunous** [comment]
The question is how many such forks there are? If there is only few then I don't see a need to move them somewhere else. Just making sure that a specific version won't disappear suddenly should be enough.

**Comment by AbsurdlySuspicious** [comment]
> If there is only few then I don't see a need to move them

Let's keep it as is for the time being then

**Comment by saket** [comment]
I was reading Jitpack's FAQ today and it's interesting that they claim to keep built artifacts around forever. This is clearly not the case?

![image](https://user-images.githubusercontent.com/2387680/104855016-2ca31e80-58d8-11eb-8e2f-e5d3aa08ce22.png)

**Comment by AbsurdlySuspicious** [comment]
I've been searching for similar issues back then and I'd say it happens rather occasionally than systematically, but it still happens so I wouldn't say jitpack is really reliable in that matter

**Comment by jitpack-io** [comment]
Hi,

Came here to address the issue about deleted artifacts. 
They can be deleted by users within the first 7 days but after that become 'frozen'.
The 404 was likely caused by a network/infrastructure issue which we are continuously working on improving.
At the moment the files are still there:
https://jitpack.io/com/github/rahatarmanahmed/circularprogressview/v2.5.0/

**Comment by thegarlynch** [comment]
Can i be here just to list some affected repo ?

com.budiyev.android:code-scanner:2.1.0
com.github.gcacace:signature-pad:1.2.1
com.google.android:flexbox:2.0.1
com.camerakit:camerakit:1.0.0-beta3.11
com.camerakit:jpegkit:0.1.0

because currently this 5 repo can't be accessed

**Comment by AbsurdlySuspicious** [comment]
@thegarlynch this discussion doesn't belong to this repo
