### ISSUE TITLE
Just a head icon of the Android logo after downloading the app

### ISSUE THREAD

**Issue by olva90** [Tunous/Dawn#325]
Hey guys i love this app. But after downloading it, no icon but a Android logo head. Please solve this problem.
Mobile: Xiaomi redmi note 4x
Android version: 7.0
miui version: 11.0.2.0
![0_IMG_20200907_122351](https://user-images.githubusercontent.com/70996045/92555892-7c1e7180-f28a-11ea-9458-657499f3a9e2.jpg)

**Comment by Tunous** [comment]
Fixed by https://github.com/Tunous/Dawn/pull/318
