### ISSUE TITLE
App crashes on reply

### ISSUE THREAD

**Issue by userhs6719** [Tunous/Dawn#343]
**Describe the bug**
"reply" causes app to crash

**To Reproduce**
Tap floating reply button on thread or reply on comment swipe gesture

**URLs of affected threads**
All threads, all comments

**Expected behavior**
expect reply

**Screenshots**
https://i.imgur.com/uqzKG5n.png

**Smartphone (please complete the following information):**
 - Device: HTC one m8
 - OS: Android 6
 - Version 6.20.654.3

**Additional context**
I guess I'm using an outdated os

**Comment by AbsurdlySuspicious** [comment]
Seems like it's same as #187

**Comment by Tunous** [comment]
Closed as duplicate
