### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by GrbavaCigla** [Tunous/Dawn#412]
Is this project still alive?

**Comment by victorz** [comment]
Last release was just over a month ago and the last commit to master was 10 days ago so I'd say so? You could have checked this yourself. :+1:

**Comment by AbsurdlySuspicious** [comment]
[Yeah.](https://github.com/Tunous/Dawn/graphs/commit-activity)

**Comment by GrbavaCigla** [comment]
Yeah, sorry. last commits were by dependabot and I thought it isn't actively maintained.
