### ISSUE TITLE
app frequently crashes if I watch a video from the main page

### ISSUE THREAD

**Issue by teasus-spiced** [Tunous/Dawn#421]
If I watch a video by tapping on the preview without first going to the post then press the back button, the app becomes unresponsive and freezes; eventually I get the message that it has stopped working and can kill the app. I uninstalled and reinstalled the app to no avail.

Nokia 7 plus, Android 10 unmodified

**Comment by AbsurdlySuspicious** [comment]
Can't reproduce yet on Android 9. Does this happen if you close video player by swiping it up or down instead of pressing back?

**Comment by teasus-spiced** [comment]
It had been happening a lot but I can't get it to go wrong again! Not long after this an update came down and I applied it, so maybe that fixed it? I guess I should close this now
