### ISSUE TITLE
support Customs Feeds

### ISSUE THREAD

**Issue by datesastick** [Tunous/Dawn#422]
**Is your feature request related to a problem? Please describe.**
In the original Reddit app I have grouped some subreddits to a "Custom Feed".

**Describe the solution you'd like**
A button under "Dawn" like "Frontpage", "Popular" or all my subscribed subreddits, where I can select my "custom feed".

![Screenshot_20210404-230641](https://user-images.githubusercontent.com/69542959/113521555-7ed01380-959a-11eb-8fe1-2a6eac126cec.png)

**Comment by AbsurdlySuspicious** [comment]
I presume "Custom feeds" is same thing as multi-reddits? If so, this is a duplicate of #249

**Comment by datesastick** [comment]
Oh yeah. I didn't know the term "multi-reddits"
