### ISSUE TITLE
Reddit post still active after closing

### ISSUE THREAD

**Issue by ByteBitten** [Tunous/Dawn#431]
The bug:
After viewing a post (with video/sound) and you click it away, it is still 'active' in the background.
With autoplay video's (like YT), it plays the next video.

**URLs of affected threads**
https://reddit.com/r/instantkarma/comments/mt69s5/law_laid_down_on_biker_with_terrible_attitude/
Notices it with Youtube Posts

**Expected behavior**
Close post, no autoplay

**Smartphone:**
 - Device: Nokia 8 TA-1004
 - OS: Android 9
 - Version v0.12.2

It is not the same as, but is possibly related to #124 and #268 
Those are of the main scroll screen, not the post view.

**Comment by AbsurdlySuspicious** [comment]
Eh? Dawn doesn't play YT videos itself, it shows them as links

**Comment by ByteBitten** [comment]
After checking, I found it is my webview-browser, indeed.
