### ISSUE TITLE
Loggin out is an option even though no account is logged in, feed disappears after

### ISSUE THREAD

**Issue by IHateTheProgrammingClass** [Tunous/Dawn#483]
**Describe the bug**

**To Reproduce**

0. No account is added
1. Click account icon, logout option exist, confirm logout, click done.
2. At this point the logout option appears again in the account menu
3. Refresh
4. "Whoops something went wrong", feed disappears
5. Restart app, everythings back to normal

**URLs of affected threads**
This section is essential for any content or media related bugs.
Include at least one url or otherwise omit this section if not applicable.

--

**Expected behavior**

No logout option is possible if accounts are not added.

**Screenshots**

![Screenshot_20210707-112754_Dawn](https://user-images.githubusercontent.com/85404737/124736848-efbef880-df06-11eb-9d72-ece8d496fdcd.png)

![Screenshot_20210707-112810_Dawn](https://user-images.githubusercontent.com/85404737/124736868-f3eb1600-df06-11eb-8fad-78fd14db12b6.png)

![Screenshot_20210707-112842_Dawn](https://user-images.githubusercontent.com/85404737/124736879-f51c4300-df06-11eb-8af9-4ad7711a440d.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 3]
 - OS: Android, Lineage 17.1
 - Version: 10

**Additional context**
Add any other context about the problem here. (Link to submission, name of subreddit.)

**Comment by AbsurdlySuspicious** [comment]
Dup of #358 too
