### ISSUE TITLE
Support for iOS

### ISSUE THREAD

**Issue by dtantono** [Tunous/Dawn#598]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Support for iOS

**Describe alternatives you've considered**
There is a slide for iOS (https://github.com/Haptic-Apps/Slide-iOS) But, I feel Dawn is much more responsive

**Comment by msfjarvis** [comment]
There's no way to support iOS outside of building an entirely separate app from scratch which is outside the scope of the project.
