### ISSUE TITLE
Add method for removing vote

### ISSUE THREAD

**Issue by brainchild0** [Tunous/Dawn#628]
Voting on an item occurs by swiping it to left. The distance of the swipe determines an up vote versus down.

No method is apparent for removing existing votes.

Observations are made on version 0.12.3.

**Comment by AbsurdlySuspicious** [comment]
Just swipe to the same reaction again to remove the vote. 
If submission is upvoted, make short swipe left to remove upvote, or fo it's downvoted - long swipe to remove downvote

**Comment by brainchild0** [comment]
I understand, based on the explanation, that removing a vote is possible in principle. Yet, doing so depends on the user's knowing the current vote status, and selecting the same action a second time. Currently, no interactivity, in terms of status information, is aiding the user.

I recommend in the case of a vote being active, removing the up and down vote actions and replacing both with a single action for removing any vote.

**Comment by AbsurdlySuspicious** [comment]
Current vote status is clearly visible with up/down vote icon and font color in comment and submission bylines. This behavior basically reflects behavior of web version of reddit, where second click on up/down vote button removes the vote.

**Comment by brainchild0** [comment]
I believe the user experience for the two cases is not plainly comparable. 

On the web interface, changing the voting status occurs through direct interaction with the indicator.

Through the swipe-based design, the action and the indicator are separate, such that coordination of the two, reviewing the status versus changing it, requires further effort by the user.
