### ISSUE TITLE
F-Droid support

### ISSUE THREAD

**Issue by vinz243** [Tunous/Dawn#66]
Since this is open source, why not release it on F-Droid. Would be nice

**Comment by Tunous** [comment]
Yes, that will be done. I've prepared everything for F-Droid release and it will go together with Play Store release. I just want #8 to come first.

**Comment by JonnyHaystack** [comment]
I notice it is released on the Play Store but still not on F-Droid?

**Comment by elenmerbau** [comment]
@JonnyHaystack need to finish with app rebranding first.

**Comment by federa7675** [comment]
Hello @Tunous 

Thanks for keeping this project alive

There is a "Requests For Packaging" for dawn in the f-droid repo and everything is well, there are some little things remaining you can read about here: https://gitlab.com/fdroid/rfp/-/issues/1320#note_331543140

I can help with making the "Fastlane file structure" and do a pr if you agree?

**Comment by Tunous** [comment]
@federa7675 Thanks for the info! Feel free to create a pull request for that, I'll gladly accept it.

**Comment by federa7675** [comment]
Do you like the idea of removing the bugsnag or no?

**Comment by Tunous** [comment]
Configuration of that should be split to 2 versions. One for Play Store where Bugsnag would stay and the other for F-Droid without.

**Comment by federa7675** [comment]
Oh that's good to hear you're interested!

I would like to know if I should use the same app icons and screenshots as playstore or something else from the re-branding?

**Comment by Tunous** [comment]
Unfortunately we never received finished assets from this rebranding. For now we still have to use the current “Dank” ones.

**Comment by federa7675** [comment]
Do you have high quality app icon and screenshots, I couldn't find them in the repo (Only 192px x 192px app icon).

I could technically download screenshots from google play but they are in webp format and low quality, so thought to ask you before pr?

**Comment by Tunous** [comment]
We now have a proper icon that could be used.

**Comment by Tunous** [comment]
I marked this with “help wanted” label as I personally never released apps to F-Droid and don’t remember anymore what needs to be done for it to work.

**Comment by IzzySoft** [comment]
@Tunous I just got notified via IRC. At the RFP, we're still waiting for your answer concerning that JAR file, which is why it's stuck. To help it "take off", on "special demand" I've added it to my repo for now – should [show up here](https://apt.izzysoft.de/fdroid/index/apk/me.thanel.dank) with the next sync tomorrow.

While on it, your Fastlane might need a little rework:

* `featureGraphic.jpeg` has unsupported dimensions. It should be either 1024x500 or 512x250 pixels. For my repo, I've cropped it and adjusted to the latter.
* `changelogs/*.txt` are missing for the last 4 releases
* `short_description.txt` looks a bit "thunderous" (forgive me) instead of "informal". I'd suggest to change that to e.g. "unofficial client for Reddit".
* `full_description.txt` just points out your app is a fork and properly gives attribution (which is great!) – but misses to describe what the app is about. If you want to, you could copy-paste what I've setup for my repo:

```markdown
This is an open-source fork of <a href='https://github.com/saket/dank'>Dank for Reddit</a> originally created by Saket Narayanm.

As <i>Dank</i> did, <i>Dawn</i> puts the focus on user-generated content. The UI takes a back-seat so that you can enjoy photos posted by Reddit’s lovely users in their full glory. It is driven by gestures. Unlike taps, gestures enable faster navigation, are easier to build muscle memories for (because of their larger surface areas) and most important of all — they are downright enjoyable.

While going all-in on gestures, <i>Dawn</i> still ensures that they’re consistent. Vertical gestures are used for navigation. Horizontal gestures are used for actions like voting or scrolling through an Imgur album.

Further features include:

* Drag to dismiss screens
* Inline replies
* Live Markdown
* Undo
* GIFs
* Rich media notifications
```

(as for formatting of this, please [see my wiki](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) with some details)

**Comment by M86xKC** [comment]
If other issues (the .jar file and bugsnag) are resolved, I can add the missing changelogs 🙂

**Comment by IzzySoft** [comment]
The last one will suffice. Currently, F-Droid uses the latest one only. For my repo, I've constructed it from the releases page (you will see it tomorrow).

**Comment by Tunous** [comment]
Thanks for the info, I was not aware of these issues. I'll try to look at the jar file and bugsnag sometime during this week. 

@M86xKC Great, if you are willing then feel free to make a pull request with fixed changelog.

**Comment by M86xKC** [comment]
Done! #345

**Comment by IzzySoft** [comment]
So I assume all should be ready now? I'll trigger a rescan at our end then to see what the fdroid-bot has to say. Again, for reference: [Here's the RFP](https://gitlab.com/fdroid/rfp/-/issues/1320).

**Comment by Tunous** [comment]
Right, I kind of forgot about this one again... Thanks for picking it up.

I didn't get myself to remove Bugsnag yet but the main concern regarding jar lib was resolved on master. Unless it's necessary to remove Bugsnag or make a new release then it's good to go.

**Comment by IzzySoft** [comment]
Is bugsnag configured opt-in, or active by default? Of course, preferably it's simply "not there at all" – but it's to a degree "acceptable". Might raise the `Tracking` AntiFeature, though.

**Comment by Tunous** [comment]
@IzzySoft I've removed use of bugsnag in https://github.com/Tunous/Dawn/pull/357

**Comment by IzzySoft** [comment]
That's great, thanks! Can we have a new tag at the top of all these changes? Then I'd kick the bot again at our end (which looks at the top-most tag, hence the need for a new one) and hopefully have it confirm, so I can set up metadata and we might be able to get your app listed soon!

**Comment by Tunous** [comment]
@IzzySoft Done, 0.12.0 with all changes is live.

**Comment by IzzySoft** [comment]
Thanks @Tunous – confirming Bugsnag being gone, removed `Tracking` in my repo (ugh, replaced it by `NonFreeNet` actually, which I forgot before – needed due to Reddit). [MR on its way](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8106).

**Comment by IzzySoft** [comment]
And [there you go](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8106#note_482130542)! In a few days, Dawn should show up at F-Droid. About a week after that, I usually remove apps from my repo unless explicitly asked to keep them. Find some background, pros and cons [in this wiki page](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ). Then let me know if you need it to stay :wink:

**Comment by M86xKC** [comment]
Yay! Dawn in now on F-Droid. 🥳🎉
@Tunous the issue can be closed

**Comment by Tunous** [comment]
Great, thanks for help on this.

**Comment by IzzySoft** [comment]
Congrats!

@Tunous Now it's available at F-Droid.org directly I'd give it a week's overlap and then remove your app from my repo, as usual – unless you want it to stay for some reason. If you want it to stay, just say so within a week.

**Comment by Tunous** [comment]
@IzzySoft People requested just for the app to be on F-Droid and I don't see anything that would require the app to be on both repos so I guess it can be removed 🤷‍♂️.

But, I personally don't use F-Droid or similar so I don't have strong opinions on this. For me it could either stay or not unless it's more work for someone to keep it here.

**Comment by IzzySoft** [comment]
Well, you can find the pros and cons [in my wiki](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ). Basically, if you have a fast paced release cycle (more than 1 or 2 releases per week) and your users insist on fast updates, they might wish it available in mine. It also enables easy cross-updates from Play (for those who wish to switch), as the signature is the same – which can be achieved using "reproducible builds" with F-Droid as well (but that's some work).

So in general, most apps are best off being at F-Droid only. In a few cases (like FairEmail with multiple updates per week or sometimes even per day) it's good to have them in both – basically with the idea of "early birds" or "testers". So some apps also have special test builds in mine (as my repo picks them up faster), and the stable builds at F-Droid.

I'd say we take the "normal approach" here now, removing it from my repo. Should there be demand, we can add it back anytime.
