### ISSUE TITLE
Adaptive Icon

### ISSUE THREAD

**Issue by rodrigoswz** [Tunous/Dawn#78]
Please, add a better and adaptive icon.

The current one is not bad, but its resolution/quality is very poor (this is especially noticeable in splash screen).

And besides, it's not adaptive like all my other apps.

**Comment by saket** [comment]
Wanna send a PR?

**Comment by Tunous** [comment]
We now have an adaptive icon thanks to https://github.com/Tunous/Dawn/pull/212.
