### ISSUE TITLE
Ability to select and copy comment text

### ISSUE THREAD

**Issue by mtaki14** [Tunous/Dawn#81]
Please add a way to select and copy text from comments. Maybe by long pressing at a comment it grants the ability to start selecting text, that seems sensible enough. Or for a start, a simple option in the additional options menu (swipe fully right) to copy the whole comment text.

**Comment by Tunous** [comment]
Implemented in 3 places by @AbsurdlySuspicious

- Inline text selection (#177)
- Submission title selection (#182)
- Selftext selection (#178)
