### ISSUE TITLE
Typing comment lag

### ISSUE THREAD

**Issue by PootisPaw** [Tunous/Dawn#92]
There is a weird lag when typing a comment. I cannot really explain much, so there is a video below showcasing the problem. 
https://gfycat.com/spanishfoolhardyafricanwildcat

**Comment by krux3r** [comment]
I can approve that. Been experiencing that from the beggining.

My device is Huawei P10 Lite, rooted 8.0.

**Comment by Esselans** [comment]
Seems to be the live markdown. See #9

**Comment by Tunous** [comment]
Marking as duplicate of #9
